name: milou_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auth_service:
    path: packages/auth_service

  cupertino_icons: ^1.0.2
  audioplayers: ^1.0.1
  tuple: ^2.0.0
  localstorage: any
  shared_preferences: any
  flat_icons_flutter: ^1.0.2
  intl: ^0.17.0
  firebase_storage: ^10.3.4
  firebase_auth: ^3.6.2
  firebase_core: ^1.10.0
  firebase_auth_platform_interface: any
  cloud_firestore: any
  firebase_database: any
  flutter_spinkit: ^5.1.0
  flutter_lints: ^2.0.0
  flutterfire_ui: any

flutter:

  uses-material-design: true

assets:
  - assets/audio/clicker.mp3