name: milou_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auth_service:
    path: packages/auth_service

  cupertino_icons: ^1.0.5
  audioplayers: ^1.0.1
  tuple: ^2.0.0
  shared_preferences: ^2.0.15
  flat_icons_flutter: ^1.0.2
  intl: ^0.17.0
  firebase_auth: ^3.6.2
  firebase_core: ^1.10.0
  cloud_firestore: ^3.4.3
  firebase_database: ^9.1.0
  flutter_spinkit: ^5.1.0
  flutter_lints: ^2.0.0
  flutterfire_ui: ^0.4.3+4
  flutter_platform_widgets: ^2.0.0
  uuid: ^3.0.6
  charts_flutter: ^0.12.0
  firebase_analytics: ^9.3.0
  json_theme: ^4.0.0


flutter:
  uses-material-design: true

assets:
  - assets/audio/clicker.mp3
  - assets/appainter_theme_dark.json
  - assets/appainter_theme_light.json