// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqzOuvVEYbIDXgs1OmmFkKrsmZBtTDWZM',
    appId: '1:953201047309:web:ac22be7a23f05538632244',
    messagingSenderId: '953201047309',
    projectId: 'milou-4b168',
    authDomain: 'milou-4b168.firebaseapp.com',
    storageBucket: 'milou-4b168.appspot.com',
    measurementId: 'G-S57KMW4DZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByRTJklW6K2BZwQKEVepnW4tVnUSYx_Rs',
    appId: '1:953201047309:android:a9cd39fdde5cbc38632244',
    messagingSenderId: '953201047309',
    projectId: 'milou-4b168',
    storageBucket: 'milou-4b168.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD81qwjjXvi0Bo9PY9lwGzj_oy6Rh-6q6M',
    appId: '1:953201047309:ios:9737cfad41704071632244',
    messagingSenderId: '953201047309',
    projectId: 'milou-4b168',
    storageBucket: 'milou-4b168.appspot.com',
    iosClientId: '953201047309-ncm7cn9bcvf5j8u33eehie30nrl9v80h.apps.googleusercontent.com',
    iosBundleId: 'com.example.milouApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD81qwjjXvi0Bo9PY9lwGzj_oy6Rh-6q6M',
    appId: '1:953201047309:ios:9737cfad41704071632244',
    messagingSenderId: '953201047309',
    projectId: 'milou-4b168',
    storageBucket: 'milou-4b168.appspot.com',
    iosClientId: '953201047309-ncm7cn9bcvf5j8u33eehie30nrl9v80h.apps.googleusercontent.com',
    iosBundleId: 'com.example.milouApp',
  );
}
